name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
  build:
    needs: run_tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        
      - name: Set Docker image name
        run: echo "IMAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        
      - name: Set Docker image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
