name: CI
on: [push]

jobs:
  test:
    name: sosiska blin
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{matrix.node-version}}
