name: Context testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: matrix.node-version
