name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
        
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Run tests
        run: pnpm test
  build:
    needs: run_tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Docker image name
        run: echo "IMAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        
      - name: Set Docker image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: 0xdeadc0d3/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=0xdeadc0d3/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=0xdeadc0d3/${{ env.IMAGE_NAME }}:buildcache,mode=max
